export const INC_STEP = "USER_PROFILE_INC_STEP";
export const SET_STATE = "USER_PROFILE_SET_STATE";
export const SET_FIRST_NAME = "USER_PROFILE_SET_FIRST_NAME";
export const SET_LOADING = "USER_PROFILE_SET_LOADING";
export const LOAD = "USER_PROFILE_LOAD";
export const SET_USERINFO = "USER_PROFILE_SET_USERINFO";
export const SET_AVATAR_URL = "USER_PROFILE_SET_AVATAR_URL";
export const SET_INPROCESS = "USER_PROFILE_SET_INPROCESS";

export const SET_SUBMISSION_ERROR = "USER_PROFILE_SET_SUBMISSION_ERROR";
